### ISSUE TITLE
ERROR: Unknown database backend: sqlite

### ISSUE THREAD

**Issue by johnharris85** [ankyra/escape-inventory#2]
Running `docker run -P -it ankyra/escape-inventory:v0.12.32` gives me some output ending in:

    2017/12/12 14:18:20 INFO: Loading configuration file '/etc/escape-inventory/config.json
    2017/12/12 14:18:20 INFO: Activating 'sqlite' database
    2017/12/12 14:18:20 ERROR: Unknown database backend: sqlite

Not sure exactly where this issue is manifesting, as it looks like sqlite is set as the default in the code, and the default config, so maybe a version mismatch, or something that wasn't deployed to that image yet? *shrugs* :)

**Comment by bspaans** [comment]
Hi John , 

Thanks for the report. Good spot. Looks like this slipped through when we swapped out the sqlite backend for ql. I forgot to update the default configuration persisted in the Docker image, which I'll fix now and push live. Until that time a workaround would be to add `-e DATABASE=ql` to the docker command.

Thanks, 
Bart

**Comment by johnharris85** [comment]
Thanks @bspaans, sounds good :)

**Comment by bspaans** [comment]
The new image is live with version v0.12.34. 

Looks like `docker run -P -it ankyra/escape-inventory:v0.12.34` actually comes up this time so closing this issue. Thanks again for the report.
